apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.12.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: casskop.v2.1.9
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: casskop
  displayName: casskop
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cassandra
  links:
  - name: Casskop
    url: https://github.com/cscetbon/casskop
  maturity: alpha
  provider:
    name: casskop
  version: 2.1.9
