{{- if .Values.rbacEnable }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "multi-casskop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "multi-casskop.name" . }}
rules:
- apiGroups:
  - db.orange.com
  resources:
    - multicasskops
    - cassandraclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
- apiGroups:
    - db.orange.com
  resources:
    - multicasskops/status
    - cassandraclusters/status
  verbs:
    - get
    - update
    - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
{{- end }}
