name: Deploy to GitHub Pages

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
    tags: ["*"]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17.7.2
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build