name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add configuration file
        run: |
          cat <<EOF > .golangci.yml
          run:
            timeout: 5m
            issues-exit-code: 0
          linters-settings:
            gosimple:
              checks:
                - all
                - '-S1023'
          issues:
            exclude-rules:
              - path: .+_test.go
                text: "package sigs.k8s.io/controller-runtime/pkg/client/fake is deprecated: please use pkg/envtest"
              - path: .+(_test|mock_client).*.go
                text: "is not checked"
          EOF
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.48.0
